version: "3.8"

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/MyProductivityBoard
    command: php -S 0.0.0.0:80 -t /MyProductivityBoard
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1910932882
      MYSQL_DATABASE: db_MyProductivityBoard
  node:
    image: node:lts
    user: node
    command: tail -f /dev/null
    volumes:
      - ./:/MyProductivityBoard
    working_dir: /MyProductivityBoard
    environment:
      - "NODE_ENV=development"


